apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: author-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: author
    spec:
      containers:
      - name: author
        image: newmaster/kubecourse-author
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: author
  labels:
    app: author
spec:
  selector:
    app: author
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30003
  type: LoadBalancer