apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: books-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: newmaster/kubecourse-books
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    app: books
spec:
  selector:
    app: books
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer